name: ci-macos

# Trigger the workflow on push or pull request
on:
  pull_request:
    # branches: [master]
  push:
    paths:
      - '.github/workflows/ci-macos.yml'
      - 'stack*.yaml'
      - '*.cabal'
      - 'src/**'
      - 'test/**'
      - 'cbits/**'

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - "9.4"
          - "9.2"
          - "9.0"
          - "8.10"
          - "8.8"
          - "8.6"
    env:
      STACK_FLAGS: "--flag accelerate:nofib"
      HADDOCK_FLAGS: "--haddock --no-haddock-deps --no-haddock-hyperlink-source --haddock-arguments=\"--no-print-missing-docs\""

    steps:
      - uses: actions/checkout@v3

      - run: ln -s stack-${{ matrix.ghc }}.yaml stack.yaml

      - uses: actions/checkout@v3
        with:
          repository: actions/cache
          path: .github/actions/cache-always
          ref: v3

      # Tweak `action.yml` of `actions/cache@v3` to remove the `post-if`
      # condition, making it default to `post-if: always ()`.
      - name: Set up actions/cache-always@v3
        run: |
          sed -i -e '/ post-if: /d' .github/actions/cache-always/action.yml

      - name: actions/cache-always@v3
        uses: ./.github/actions/cache-always
        with:
          path: snapshot.pkgdb
          key: ${{ runner.os }}-${{ matrix.ghc }}-snapshot.pkgdb

      - name: actions/cache-always@v3
        uses: ./.github/actions/cache-always
        with:
          path: |
            ~/.local/bin
            ~/.stack/programs
            ~/.stack/snapshots
            .stack-work
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('stack.yaml') }}-${{ hashFiles('snapshot.pkgdb') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('stack.yaml') }}-${{ hashFiles('snapshot.pkgdb') }}
            ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('stack.yaml') }}-
            ${{ runner.os }}-${{ matrix.ghc }}-

      # - name: Install stack
      #   run: |
      #     if [[ ! -x ~/.local/bin/stack ]]; then
      #       brew install gnu-tar
      #       curl -sL https://get.haskellstack.org/stable/osx-x86_64.tar.gz | gtar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      #       chmod a+x ~/.local/bin/stack
      #     fi

      - name: Setup stack
        run: |
          mkdir -p ~/.local/bin
          mkdir -p ~/.stack/hooks
          curl https://raw.githubusercontent.com/haskell/ghcup-hs/master/scripts/hooks/stack/ghc-install.sh > ~/.stack/hooks/ghc-install.sh
          chmod +x ~/.stack/hooks/ghc-install.sh
          echo "~/.local/bin" >> $GITHUB_PATH

      - name: Install GHC
        run: stack setup --install-ghc

      - name: Build dependencies
        run: stack build $STACK_FLAGS --test --no-run-tests --only-dependencies

      - name: Build
        run: stack build $STACK_FLAGS $HADDOCK_FLAGS --test --no-run-tests

      # currently broken with linker error -TLM 2021-06-25
      # - name: Test doctest
      #   run: stack test accelerate:doctest $STACK_FLAGS

      - name: Test nofib
        run: stack test accelerate:nofib-interpreter $STACK_FLAGS

      # - name: Test haddock generation
      #   run: stack haddock --haddock --no-haddock-deps --no-haddock-hyperlink-source --haddock-arguments="--no-print-missing-docs" $STACK_FLAGS

      - name: Save snapshot.pkgdb
        run: stack exec ghc-pkg -- --package-db=$(stack path --snapshot-pkg-db) list > snapshot.pkgdb

