#!/bin/bash

GHC_CORE=`which -a ghc-core | grep -v "\./ghc-core"`

$GHC_CORE --no-cast --no-asm -- \
          -odir dist/build -hidir dist/build \
          -optP -include -optP dist/build/autogen/cabal_macros.h \
          -iutils -Iinclude \
          -O2 \
          $@

