#!/bin/bash

# Get cabal to load up ghci for us. This will set the environment appropriately
# if we have a local sandbox installation.
#
GHC="cabal exec ghc --"
DIR=`dirname $0`

# Attempt to load all accelerate packages from source. Note that programs that
# provide visualisations might require 'gloss' to be installed with the GLFW
# backend to work properly within GHCi.
#
GHC_FLAGS="$GHC_FLAGS
    -optP -include -optP $DIR/dist/build/autogen/cabal_macros.h
    -optP -include -optP $DIR/../accelerate-cuda/dist/build/autogen/cabal_macros.h
    -i$DIR/utils
    -i$DIR/lib
    -i$DIR/../accelerate
    -i$DIR/../accelerate-cuda
    -i$DIR/../accelerate-io
    -i$DIR/../accelerate-fft
    -DACCELERATE_DEBUG
    -DACCELERATE_BOUNDS_CHECKS
    -DACCELERATE_INTERNAL_CHECKS
    -DACCELERATE_CUDA_BACKEND"

$GHC $GHC_FLAGS $@

