-- Helper script to shadow that automatically generated by cabal, but pointing
-- to our local development directory.
--

module Paths_accelerate_cuda where

import Data.Version
import System.Directory
import System.FilePath

version :: Version
version = Version {versionBranch = [2,0,0,0], versionTags = ["dev"]}

getDataDir :: IO FilePath
getDataDir = do
  base <- getCurrentDirectory
  return $ takeDirectory base </> "accelerate-cuda"

